### ISSUE TITLE
Some methods should use Any instead AnyObject

### ISSUE THREAD

**Issue by roman-sinelnikov** [ptiz/bender#17]
I.e. 
public protocol Rule {
    associatedtype V
    func validate(_ jsonValue: AnyObject) throws -> V
    func dump(_ value: V) throws -> AnyObject
}

**Comment by ptiz** [comment]
Please provide a rationale

**Comment by dydus0x14** [comment]
<img width="1050" alt="screen shot 2018-10-03 at 12 29 48 am" src="https://user-images.githubusercontent.com/8783235/46378501-771b1580-c6a4-11e8-9656-15672a3d01a3.png">

Every objects to dump (except AnyObject) requires casting to AnyObject. Changing signature of Rule protocol to Any would fix such compile error

**Comment by ptiz** [comment]
Incorporated in 2.0.0
