### ISSUE TITLE
Nontrivial behavior of using optional parameters with proxy rules.

### ISSUE THREAD

**Issue by dydus0x14** [ptiz/bender#6]
There is an json object with "bottomLevelKey" = null.
Actual behavior of validation using testRule described below: validation fails. 
Expected behavior: validation finishes successfully because testRule contains only .optional parameters.
`
let testRule = ClassRule(YourModel()).optional("topLevelKey", rule(StringRule, atPath: "bottomLevelKey")) { $0.value = $1 }
`

**Comment by ptiz** [comment]
Removed "rule" function and corresponding ProxyRule. Use JSONPath instead and "/" operator to construct it inline.

**Comment by ptiz** [comment]
Fixed in 1.4.0
